import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "My elective",
  description: "Generated by Bezt",
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <>{children}</>
}
