import type { Metadata } from "next"
import Header from "./components/header"
import PreQChip from "./components/pre-q-chip"

export const metadata: Metadata = {
	title: "Assessment",
	description: "Generated by Bezt",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className="bg-white h-screen w-full">
			<Header />
			<div className="bg-background text-primary px-5 h-screen w-full rounded-e-2xl">
				<PreQChip />
				{children}
			</div>
		</div>
	)
}
