import MobileNavigationBar from "@/components/shared/mobile-navigation-bar"
import type { Metadata } from "next"
import Header from "./components/header"

export const metadata: Metadata = {
	title: "More",
	description: "Generated by Bezt",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className="bg-alice-blue w-[380px] h-screen mx-auto relative z-1 overflow-y-scroll">
			<Header />
			<div>{children}</div>
			<MobileNavigationBar />
		</div>
	)
}
