import UserInfoProvider from "@/store/sing-up-provider"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Sign-up",
  description: "Generated by Bezt",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <UserInfoProvider>
      <div className="bg-alice-blue w-[380px] p-5 pt-0 no-scrollbar h-screen mx-auto relative z-1 overflow-y-scroll">
        <div>{children}</div>
      </div>
    </UserInfoProvider>
  )
}
