import type { Metadata } from "next"

import RankingsDataProvider from "@/store/ranking-provider"
import { Suspense } from "react"

export const metadata: Metadata = {
  title: "Rankings",
  description: "Generated by Bezt",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <RankingsDataProvider>
      <Suspense>
        <div>{children}</div>
      </Suspense>
    </RankingsDataProvider>
  )
}
