export const craft = [
  {
    heading: "Industry Awareness",
    subHeading: "craft series",
    proficiencies: ["Media & Entertainment", "Chemicals", "Food & FMCG"],
  },
  {
    heading: "Academic Mastery",
    subHeading: "craft series",
    proficiencies: [
      "Class 8, 9 and 10",
      "Class 11, 12 - PCM",
      "Engineering (Core)",
    ],
  },
]

export const extra = [
  {
    heading: "Digital Cognizance",
    subHeading: "Extra series",
    proficiencies: [
      "Internet Security",
      "Quantum Computing",
      "Spreadsheet Tools",
    ],
  },
  {
    heading: "Lingual Proficiency",
    subHeading: "extra series",
    proficiencies: ["Spanish", "Telugu", "Malayalam"],
  },
]

export const skill = {
  selections: [
    "Programming Languages",
    "Version Control Systems",
    "Software Development Frameworks",
  ],
}

export const otherOptions = {
  "A-E": [
    "API integration",
    "Databases",
    "Cloud Platforms",
    "Infrastructure as Code (IaC)",
    "Containerization Technologies",
    "CI/CD Pipelines",
    "Security & Compliance",
    "Data Analysis Tools",
    "Statistical Programming",
    "Machine Learning",
    "Big Data Technologies",
    "Data Visualization",
    "Computer Networking",
    "Cybersecurity",
    "Firewall & Network Security Tools",
    "Operating Systems",
    "Digital marketing",
    "Marketing analytics",
    "Content management",
    "Email marketing",
    "Social media management",
    "Financial analysis",
    "Accounting software",
    "Financial reporting",
    "Data analysis",
  ],
  "F-J": [
    "Digital marketing",
    "Marketing analytics",
    "Content management",
    "Email marketing",
    "Social media management",
    "Financial analysis",
    "Accounting software",
    "Financial reporting",
    "Data analysis",
    "API integration",
    "Databases",
    "Cloud Platforms",
    "Infrastructure as Code (IaC)",
    "Containerization Technologies",
    "CI/CD Pipelines",
    "Security & Compliance",
    "Data Analysis Tools",
  ],
  "K-O": [
    "Statistical Programming",
    "Machine Learning",
    "Big Data Technologies",
    "Data Visualization",
    "Computer Networking",
    "Cybersecurity",
    "Firewall & Network Security Tools",
    "Operating Systems",
  ],
  "P-T": [
    "Data Visualization",
    "Computer Networking",
    "Cybersecurity",
    "Firewall & Network Security Tools",
    "Operating Systems",
    "Infrastructure as Code (IaC)",
    "Containerization Technologies",
    "CI/CD Pipelines",
    "Security & Compliance",
    "Data Analysis Tools",
  ],
  "U-Z": [
    "Big Data Technologies",
    "Data Visualization",
    "Computer Networking",
    "Cybersecurity",
    "Firewall & Network Security Tools",
  ],
  Others: [
    "Financial reporting",
    "Data analysis",
    "API integration",
    "Databases",
    "Cloud Platforms",
    "Statistical Programming",
  ],
}
